# Padding, embedding and packing

In [82]:
import pandas as pd

real_replay = pd.read_pickle("../data/RetailRocket/replay_buffer.df")
real_replay.head(10)

state  len_state  action  \
0  [70852, 70852, 70852, 70852, 70852, 70852, 708...          1   49432   
1  [49432, 70852, 70852, 70852, 70852, 70852, 708...          1   49432   
2  [49432, 49432, 70852, 70852, 70852, 70852, 708...          2   39563   
3  [49432, 49432, 39563, 70852, 70852, 70852, 708...          3   32776   
4  [49432, 49432, 39563, 32776, 70852, 70852, 708...          4   52161   
5  [49432, 49432, 39563, 32776, 52161, 70852, 708...          5   52161   
6  [49432, 49432, 39563, 32776, 52161, 52161, 708...          6   32776   
7  [49432, 49432, 39563, 32776, 52161, 52161, 327...          7   49432   
8  [70852, 70852, 70852, 70852, 70852, 70852, 708...          1    9750   
9  [9750, 70852, 70852, 70852, 70852, 70852, 7085...          1   38594   

   is_buy                                         next_state  len_next_states  \
0       0  [49432, 70852, 70852, 70852, 70852, 70852, 708...                1   
1       0  [49432, 49432, 70852, 70852, 70852, 70852, 708...                2   
2       0  [49432, 49432, 39563, 70852, 70852, 70852, 708...                3   
3       0  [49432, 49432, 39563, 32776, 70852, 70852, 708...                4   
4       0  [49432, 49432, 39563, 32776, 52161, 70852, 708...                5   
5       0  [49432, 49432, 39563, 32776, 52161, 52161, 708...                6   
6       0  [49432, 49432, 39563, 32776, 52161, 52161, 327...                7   
7       0  [49432, 49432, 39563, 32776, 52161, 52161, 327...                8   
8       1  [9750, 70852, 70852, 70852, 70852, 70852, 7085...                1   
9       0  [9750, 38594, 70852, 70852, 70852, 70852, 7085...                2   

   is_done  
0    False  
1    False  
2    False  
3    False  
4    False  
5    False  
6    False  
7     True  
8    False  
9    False

In [30]:
my_replay = pd.read_pickle("../data/RetailRocket/replay_buffer_replica.df")
my_replay.head(10)

state  action  \
742616   [70852, 70852, 70852, 70852, 70852, 70852, 708...   49432   
735273   [49432, 70852, 70852, 70852, 70852, 70852, 708...   49432   
737711   [49432, 49432, 70852, 70852, 70852, 70852, 708...   39563   
726292   [49432, 49432, 39563, 70852, 70852, 70852, 708...   32776   
737615   [49432, 49432, 39563, 32776, 70852, 70852, 708...   52161   
735202   [49432, 49432, 39563, 32776, 52161, 70852, 708...   52161   
742485   [49432, 49432, 39563, 32776, 52161, 52161, 708...   32776   
728288   [49432, 49432, 39563, 32776, 52161, 52161, 327...   49432   
1133190  [70852, 70852, 70852, 70852, 70852, 70852, 708...    9750   
1135980  [9750, 70852, 70852, 70852, 70852, 70852, 7085...   38594   

                                                next_state  action_type  \
742616   [49432, 70852, 70852, 70852, 70852, 70852, 708...            0   
735273   [49432, 49432, 70852, 70852, 70852, 70852, 708...            0   
737711   [49432, 49432, 39563, 70852, 70852, 70852, 708...            0   
726292   [49432, 49432, 39563, 32776, 70852, 70852, 708...            0   
737615   [49432, 49432, 39563, 32776, 52161, 70852, 708...            0   
735202   [49432, 49432, 39563, 32776, 52161, 52161, 708...            0   
742485   [49432, 49432, 39563, 32776, 52161, 52161, 327...            0   
728288   [49432, 49432, 39563, 32776, 52161, 52161, 327...            0   
1133190  [9750, 70852, 70852, 70852, 70852, 70852, 7085...            1   
1135980  [9750, 38594, 70852, 70852, 70852, 70852, 7085...            0   

         is_end  
742616    False  
735273    False  
737711    False  
726292    False  
737615    False  
735202    False  
742485    False  
728288     True  
1133190   False  
1135980   False

In [31]:
# Compare states

import numpy as np 

my_state = np.array(my_replay.state.to_list())
real_state = np.array(real_replay.state.to_list())

(my_state==real_state).any(1).sum() == len(real_replay)

True

In [32]:
my_next = np.array(my_replay.next_state.to_list())
real_next = np.array(real_replay.next_state.to_list())

(my_next==real_next).any(1).sum() == len(real_replay)

True

In [33]:
(my_replay.action.values==real_replay.action.values).sum()  == len(real_replay)

True

In [37]:
import torch
float(torch.tensor(1.35, dtype=torch.float64))

1.35

In [123]:
# Embedding exps

import torch.nn as nn 

embs = nn.Embedding(num_embeddings=4, embedding_dim=10, padding_idx=3)
print(embs.weight)
nn.init.normal_(embs.weight, 0, 0.01)
embs.weight

Parameter containing:
tensor([[-0.3885, -0.9343, -0.4991, -1.0867,  0.9624,  0.2492, -0.4845, -2.0929,
          0.0983, -0.0935],
        [ 0.2662, -0.5850, -0.3430, -0.6821, -0.9887, -1.7018, -1.2203,  1.3139,
          1.0533,  0.1388],
        [-0.2044, -2.2685, -0.9133, -0.4204,  0.2436, -0.0567,  0.3784,  1.6863,
          0.2553, -0.5496],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000]], requires_grad=True)


Parameter containing:
tensor([[ 0.0107,  0.0150, -0.0082,  0.0027, -0.0221, -0.0132, -0.0209,  0.0096,
         -0.0099,  0.0122],
        [-0.0023,  0.0134,  0.0199,  0.0137, -0.0050, -0.0028,  0.0123, -0.0110,
         -0.0097,  0.0067],
        [-0.0094, -0.0047,  0.0103, -0.0028, -0.0118, -0.0029, -0.0060,  0.0060,
         -0.0142, -0.0022],
        [ 0.0043, -0.0090, -0.0002,  0.0043, -0.0077, -0.0005, -0.0073,  0.0123,
          0.0119, -0.0022]], requires_grad=True)

In [124]:
# Still unaffected by gradient updates?
torch.manual_seed(123)
embs = nn.Embedding(num_embeddings=4, embedding_dim=5, padding_idx=3)
print(embs.weight)
result = embs(torch.tensor(0)) @ torch.tensor([10.0,10.0,0,8,0]) 
result.backward()

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  1.5810],
        [ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015],
        [ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]], requires_grad=True)


In [74]:
# The gradient of the first lookup vector changed, this is the only one 
# that was present in the computaitons
embs.weight.grad

tensor([[10., 10.,  0.,  8.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [81]:
# What happens now if we include the third row, will there 
# be a gradient?
embs.weight.grad.zero_() 
result = embs(torch.tensor(3)) @ torch.tensor([10.0,10.0,0,8,0]) 
result.backward()
embs.weight.grad

# No gradient! 

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
# Should we make it trianable? Maybe ask Martin Kuhlmann, if we set
# it to 0 that does not mean that the output is actually zero as a 
# hidden state, much more that influences that like bias, activation func,
# hidden state init, ...

In [127]:
embs(torch.tensor([0,1,2])).shape

torch.Size([3, 5])

In [248]:
# Using None 
emb = nn.Embedding(num_embeddings=4, embedding_dim=5, padding_idx=None)
print(emb.weight)

Parameter containing:
tensor([[ 0.2790, -0.7587,  0.5473,  0.4301, -0.7259],
        [ 0.7346, -0.0845,  1.0757,  0.6367, -0.1943],
        [-0.8614,  0.5338,  0.3940, -2.0565,  1.1062],
        [ 0.4562,  0.0144, -0.6411,  2.3902, -1.4256]], requires_grad=True)


In [250]:
emb = nn.Embedding(num_embeddings=4, embedding_dim=5, padding_idx=3)
print(emb.weight)

Parameter containing:
tensor([[ 0.0093, -1.8110, -0.2443,  0.1327, -0.1200],
        [ 0.4884,  1.9431,  0.2169, -0.1464, -0.4490],
        [-1.8926,  0.6000,  0.7692, -1.1323,  2.9590],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]], requires_grad=True)


In [252]:
bo = False
emb = nn.Embedding(num_embeddings=4, embedding_dim=5, padding_idx=None if bo else 3)
print(emb.weight)

Parameter containing:
tensor([[ 0.8423, -2.4813,  0.1389,  2.2357,  0.4888],
        [-0.0180,  0.8637,  0.2074,  0.5687, -0.0959],
        [ 0.0046, -1.4321,  0.0373,  0.7058,  0.2657],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]], requires_grad=True)


## Padding 

In [197]:
# Why do they need to be of same length in batch?
# Becaue the computational graph is created each forward pass
# It must be the same for all in batch!

In [262]:
# Set seeds 
import torch
torch.manual_seed(123)

In [263]:
from torch.nn.utils.rnn import pad_sequence, pad_packed_sequence, pack_padded_sequence

sent_1 = torch.tensor([1,2,3,4])
sent_2 = torch.tensor([5,6,7]) 
sent_3 = torch.tensor([8,9]) 

raw = [sent_1, sent_2, sent_3]  # batch_size = 3
padded = pad_sequence(raw, batch_first=True )  # size: [25, 3, 300]

In [264]:
print(padded.shape)
padded

torch.Size([3, 4])


tensor([[1, 2, 3, 4],
        [5, 6, 7, 0],
        [8, 9, 0, 0]])

In [265]:
# Add embedding
embed = torch.nn.Embedding(num_embeddings=10, embedding_dim=6)
print(embed.weight.shape)  # (Num_items, dim)

print(embed.weight)

torch.Size([10, 6])
Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603],
        [-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
        [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
        [-0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255],
        [-0.6315, -2.8400, -1.3250,  0.1784, -2.1338,  1.0524],
        [-0.3885, -0.9343, -0.4991, -1.0867,  0.8805,  1.5542],
        [ 0.6266, -0.1755,  1.3111, -0.2199,  0.2190,  0.2045],
        [ 0.5146,  0.9938, -0.2587, -1.0826,  0.1036, -2.1996],
        [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765]],
       requires_grad=True)


In [266]:
# Let's ask for embedding of padding and 9
print(embed(torch.tensor([0, 9])))  # Corresponging to numbers as index in table! All must be in! Not possible 10, 100 and only 2 items

tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603],
        [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765]],
       grad_fn=<EmbeddingBackward0>)


In [267]:
# Embed padded:
print(embed(padded).shape)  # (batch_size, length, dim)
embed_pad = embed(padded) 

torch.Size([3, 4, 6])


In [268]:
lengths = torch.as_tensor([4,3,2], dtype=torch.int64)
packed = pack_padded_sequence(embed_pad, lengths, batch_first=True)

print(packed)
packed.data.size() # Only keeps meaningful timesteps - 9 x embedding_size

# col wise, position 1 of sq, how many have it? 3, all. How many have position 3? 2. Last step only 1. 

PackedSequence(data=tensor([[-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
        [-0.6315, -2.8400, -1.3250,  0.1784, -2.1338,  1.0524],
        [ 0.5146,  0.9938, -0.2587, -1.0826,  0.1036, -2.1996],
        [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
        [-0.3885, -0.9343, -0.4991, -1.0867,  0.8805,  1.5542],
        [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765],
        [-0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.6266, -0.1755,  1.3111, -0.2199,  0.2190,  0.2045],
        [ 0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255]],
       grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([3, 3, 2, 1]), sorted_indices=None, unsorted_indices=None)


torch.Size([9, 6])

In [269]:
rnn = torch.nn.RNN(input_size=6, hidden_size=2, batch_first=True)  # See here: Length is NOT even an argument
padded_outp, padded_hn = rnn(embed_pad) # size: [25, 3, 2] / [1, 3, 2]

In [270]:
print("All hidden states for all time steps:",  padded_outp.shape)  # (batch_size, num_steps, hidden_size)
print("Last hidden state:",  padded_hn[0,:,:].shape, "\n")  # (batch_size, hidden_size)

print(padded_hn[0,:,:])   # Here it is SliceBackward! We jsut slice it from whole hidden states, we can pass all at once since all same length

All hidden states for all time steps: torch.Size([3, 4, 2])
Last hidden state: torch.Size([3, 2]) 

tensor([[-0.0443,  0.8260],
        [ 0.3320,  0.8101],
        [ 0.2957,  0.9264]], grad_fn=<SliceBackward0>)


In [271]:
packed

PackedSequence(data=tensor([[-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
        [-0.6315, -2.8400, -1.3250,  0.1784, -2.1338,  1.0524],
        [ 0.5146,  0.9938, -0.2587, -1.0826,  0.1036, -2.1996],
        [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
        [-0.3885, -0.9343, -0.4991, -1.0867,  0.8805,  1.5542],
        [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765],
        [-0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.6266, -0.1755,  1.3111, -0.2199,  0.2190,  0.2045],
        [ 0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255]],
       grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([3, 3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [272]:
packed_outp, packed_hn = rnn(packed) # 'PackedSequence' Obj / [1, 3, 2]
# undo_packed_outp, _ = pad_packed_sequence(packed_outp)

packed_outp.data.shape  # We only get hidden states for real data point 

torch.Size([9, 2])

In [273]:
# Same size for final hidden state - no packed tensor anymore
# We can see that only the first one has the same - which is the hidden state for 
# the undpadded seq! The others are different. 
# Also see here: The gradient func is StackBackward, they get stacked since not at similar time passing through because of diff shapes!!!
packed_hn

tensor([[[-0.0443,  0.8260],
         [ 0.5791,  0.4227],
         [-0.0802,  0.6983]]], grad_fn=<StackBackward0>)

In [274]:
# Let's see how to reproduce that:

# Can we use RNN with dioffering lengths?
examp_1 = embed(torch.tensor([[1,2], [3,4]]))
_, h = rnn(examp_1) # YES. The RNN does not care about length. This is what packed is doing
                    # Try to reproduce now:

reproduce_row_1 = embed(torch.tensor([[5,6,7]]))
reproduce_row_2 = embed(torch.tensor([[8,9]]))

_, h_1 = rnn(reproduce_row_1)
_, h_2 = rnn(reproduce_row_2)

print(torch.cat([h_1,h_2]))

# SAME result. So that means the padding indices are ignored and only the "real" data is passed.
# Very important to note. That means we can improve performance AND eliminate the influence of 
# padding items entirely on the hidden states. WOW. So padding is just a way of passing it, but 
# will have nothing to do with gradient computaitons or outputs.  

tensor([[[ 0.5791,  0.4227]],

        [[-0.0802,  0.6983]]], grad_fn=<CatBackward0>)


In [237]:
# Now just explore sorting
raw = [sent_1, sent_3, sent_2]
padded = pad_sequence(raw, batch_first=True) 
embed_pad = embed(padded)
lengths = torch.as_tensor([4,2,3], dtype=torch.int64)
packed = pack_padded_sequence(embed_pad, lengths, batch_first=True)

# Errror is raised if not sorted

RuntimeError: `lengths` array must be sorted in decreasing order when `enforce_sorted` is True. You can pass `enforce_sorted=False` to pack_padded_sequence and/or pack_sequence to sidestep this requirement if you do not need ONNX exportability.

In [238]:
raw = [sent_1, sent_3, sent_2]
padded = pad_sequence(raw, batch_first=True) 
embed_pad = embed(padded)
lengths = torch.as_tensor([4,2,3], dtype=torch.int64)
packed = pack_padded_sequence(embed_pad, lengths, batch_first=True, enforce_sorted=False)

In [241]:
_, h = rnn(packed)

h

# Exaclty same output in right ordering (but of course just chenged 2 and 3 but not sorted by len)

tensor([[[-0.0443,  0.8260],
         [-0.0802,  0.6983],
         [ 0.5791,  0.4227]]], grad_fn=<IndexSelectBackward0>)

In [255]:
# Can we add to length
lengths + 100

tensor([104, 102, 103])

In [ ]:
# For why to use no_grad for whole next_state thing. 

### Comparison with setting pading_id

Setting it to padding_id=0 - will it also be ignored in the hidden state computation?

In [303]:
# Set seeds 
import torch
torch.manual_seed(123)

raw = [sent_1, sent_2, sent_3]  # batch_size = 3
padded = pad_sequence(raw, batch_first=True)  # size: [25, 3, 300]
embed = torch.nn.Embedding(num_embeddings=10, embedding_dim=6)
emb_pad = embed(padded)
_, h = rnn(emb_pad)
h

# This is without the index

tensor([[[-0.0443,  0.8260],
         [ 0.3320,  0.8101],
         [ 0.2957,  0.9264]]], grad_fn=<StackBackward0>)

In [302]:
# Set seeds 
import torch
torch.manual_seed(123)

raw = [sent_1, sent_2, sent_3]  # batch_size = 3
padded = pad_sequence(raw, batch_first=True)  # size: [25, 3, 300]
embed = torch.nn.Embedding(num_embeddings=10, embedding_dim=6, padding_idx=0)

print(embed.weight)  # The embedding of 0 is now set to 0s everywhere

# To compare behaviour, set it to the same as initialized without the indexing
with torch.no_grad():   
    embed.weight[0] = torch.tensor([0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603])

print("\nEmbedding weights after changing manually:\n")
print(embed.weight)  # The embedding of 0 is now set to 0s everywhere

emb_pad = embed(padded)
_, h = rnn(emb_pad)
h

# This is without the index
h

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
        [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
        [-0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255],
        [-0.6315, -2.8400, -1.3250,  0.1784, -2.1338,  1.0524],
        [-0.3885, -0.9343, -0.4991, -1.0867,  0.8805,  1.5542],
        [ 0.6266, -0.1755,  1.3111, -0.2199,  0.2190,  0.2045],
        [ 0.5146,  0.9938, -0.2587, -1.0826,  0.1036, -2.1996],
        [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765]],
       requires_grad=True)

Embedding weights after changing manually:

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603],
        [-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
        [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
        [-0.1690,  0.9178,  1.5810,  1.3010,  1.275

tensor([[[-0.0443,  0.8260],
         [ 0.3320,  0.8101],
         [ 0.2957,  0.9264]]], grad_fn=<StackBackward0>)

In [316]:
# What happens if front padded?
front_pad = torch.tensor([[1,2,3,4], [0,5,6,7], [0,0,8,9]])
print(embed.weight)
front_packed = pack_padded_sequence(embed(front_pad), lengths=[4,3,2], batch_first=True)
print(front_packed)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603],
        [-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
        [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
        [-0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255],
        [-0.6315, -2.8400, -1.3250,  0.1784, -2.1338,  1.0524],
        [-0.3885, -0.9343, -0.4991, -1.0867,  0.8805,  1.5542],
        [ 0.6266, -0.1755,  1.3111, -0.2199,  0.2190,  0.2045],
        [ 0.5146,  0.9938, -0.2587, -1.0826,  0.1036, -2.1996],
        [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765]],
       requires_grad=True)
PackedSequence(data=tensor([[-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
        [ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603],
        [ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603],
        [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
        [-0.6315, -2.8400, -1.3250

In [312]:
packed # Real packed

PackedSequence(data=tensor([[-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
        [-0.6315, -2.8400, -1.3250,  0.1784, -2.1338,  1.0524],
        [ 0.5146,  0.9938, -0.2587, -1.0826,  0.1036, -2.1996],
        [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
        [-0.3885, -0.9343, -0.4991, -1.0867,  0.8805,  1.5542],
        [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765],
        [-0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.6266, -0.1755,  1.3111, -0.2199,  0.2190,  0.2045],
        [ 0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255]],
       grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([3, 3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [323]:
# Padding token will be included and other info thrown away. It is CRUCIAL to have abck padding in this context. 

In [325]:
# What happens if entirely padded?
# They use in their paper one padding token for the first 
# state since they artificially set the true_len to 1.

# KEEP THAT IN MIND!

just_pad = embed(torch.tensor([[1,2,3], [0,0,0]]))
pack_padded_sequence(just_pad, lengths=[3,0], batch_first=True)

RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0

In [29]:
# Only save embedding layer
from recommenders.SQN.gru_sqn import SQN_Network

model_examp = SQN_Network(hidden_dim=64, item_num=100, state_size=10, embedding_dim=20, action_dim=250, gamma=0.5)

In [30]:
import torch
print(model_examp.embedding.weight)
torch.save(model_examp.state_dict()["embedding.weight"], f="weightsemb.pt")

Parameter containing:
tensor([[ 0.0003, -0.0158, -0.0049,  ...,  0.0160, -0.0140,  0.0059],
        [-0.0021,  0.0112, -0.0018,  ...,  0.0153, -0.0035, -0.0159],
        [-0.0009,  0.0023, -0.0020,  ..., -0.0116,  0.0094, -0.0009],
        ...,
        [ 0.0044,  0.0015,  0.0126,  ..., -0.0024,  0.0067,  0.0147],
        [-0.0149, -0.0058, -0.0068,  ...,  0.0012,  0.0017, -0.0196],
        [ 0.0012,  0.0040,  0.0010,  ...,  0.0186,  0.0010, -0.0003]],
       requires_grad=True)


In [31]:
model_examp = SQN_Network(hidden_dim=64, item_num=100, state_size=10, embedding_dim=20, action_dim=250, gamma=0.5, )
print(model_examp.embedding.weight)
model_examp.embedding = model_examp.embedding.from_pretrained(torch.load("./weightsemb.pt"), freeze=True)
print(model_examp.embedding.weight)

Parameter containing:
tensor([[-0.0062,  0.0187, -0.0078,  ...,  0.0037, -0.0184,  0.0002],
        [ 0.0030, -0.0094,  0.0180,  ...,  0.0087, -0.0047, -0.0006],
        [ 0.0081, -0.0111,  0.0123,  ...,  0.0247, -0.0094,  0.0040],
        ...,
        [ 0.0055, -0.0126, -0.0064,  ..., -0.0025, -0.0005,  0.0065],
        [-0.0175,  0.0009, -0.0009,  ...,  0.0120, -0.0039, -0.0192],
        [ 0.0040,  0.0061,  0.0054,  ..., -0.0042,  0.0083, -0.0019]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.0003, -0.0158, -0.0049,  ...,  0.0160, -0.0140,  0.0059],
        [-0.0021,  0.0112, -0.0018,  ...,  0.0153, -0.0035, -0.0159],
        [-0.0009,  0.0023, -0.0020,  ..., -0.0116,  0.0094, -0.0009],
        ...,
        [ 0.0044,  0.0015,  0.0126,  ..., -0.0024,  0.0067,  0.0147],
        [-0.0149, -0.0058, -0.0068,  ...,  0.0012,  0.0017, -0.0196],
        [ 0.0012,  0.0040,  0.0010,  ...,  0.0186,  0.0010, -0.0003]])


In [ ]:
# YES. 